### ISSUE TITLE
Send Print error

### ISSUE THREAD

**Issue by ToolLab** [digao-dalpiaz/DzSocket#4] opened 2020-05-09 14:24 UTC
Send Print click "data error" alert.

Is there any way to send a jpg file?

**Comment by digao-dalpiaz** [comment] 2020-05-10 18:55
Hey there,

I didn't get that. Are you getting error when you are clicking at Send Print button in Demo project?

Can you specify the steps to reproduce the error, please?

Thanks.

**Comment by digao-dalpiaz** [comment] 2020-05-10 19:00
About sending JPG files, yes, of course, you can send any kind of file.
You just need to assign to a MemoryStream, and then send it.

Example:
```delphi
procedure SendJPEG;
var
  J: TJPEGImage;
  Mem: TMemoryStream;
  MS: TStringStream;
begin
  MS := TStringStream.Create;
  try
    Mem := TMemoryStream.Create;
    try
      J := TJPEGImage.Create;
      try
        J.LoadFromFile('c:\test.jpg');
        J.SaveToStream(Mem);
      finally
        J.Free;
      end;
      Mem.Position := 0;
      ZCompressStream(Mem, MS);
    finally
      Mem.Free;
    end;
    Frm.C.Send('J', MS.DataString);
  finally
    MS.Free;
  end;
end;
```

**Comment by digao-dalpiaz** [comment] 2020-06-07 00:48
I'm closing this issue because there was no further communication.

**Closed as completed by digao-dalpiaz** 2020-06-07 00:48 UTC
Labels: invalid
